In [2]:
from glob import glob
import os
import pandas as pd
import numpy as np
from PIL import Image
from sklearn.model_selection import train_test_split


In [3]:
df = []
df = pd.read_csv("HAM10000_metadata.csv")
df = df.sort_values(by="image_id")

lesion_type_dict = {
    "nv": "Melanocytic nevi",
    "mel": "Melanoma",
    "bkl": "Benign keratosis-like lesions",
    "akiec": "Actinic keratoses",
    "vasc": "Vascular lesions",
    "df": "Dermatofibroma",
}

In [12]:
image_dir = "HAM10000_images"
image_name = "ISIC_0024306.jpg"
image_path = os.path.join(image_dir, image_name)
Load_image = Image.open(image_path).convert("RGB")

nmpy_img = np.asarray(Load_image.resize((650, 450)))

[[[221 131 131]
  [222 128 126]
  [223 129 127]
  ...
  [229 134 138]
  [226 136 138]
  [230 135 139]]]


In [ ]:
image_files = []
image_files = glob("HAM10000_images/*.jpg")

image_files = sorted(image_files)

train_image = []
for i in range(0, len(image_files)):
    Load_image = Image.open(image_files[i]).convert("RGB")
    nmpy_img = Load_image.resize((650, 450))
    train_image.append(np.asarray(nmpy_img))

df = df.assign(images=train_image)

df.to_csv("HAM10000_img.csv", index=False)